# This file configures the analyzer for the Systemd Manager project.

include: package:ubuntu_lints/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    # Freezed + json_serializable compatibility
    invalid_annotation_target: ignore

    # Stricter cleanup checks
    unused_element: warning
    unused_field: warning
    unused_local_variable: warning
    dead_code: warning
    unused_import: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Additional rules for this project
    prefer_single_quotes: true
    always_use_package_imports: true
    prefer_relative_imports: false
    sort_pub_dependencies: true
    unawaited_futures: true
    avoid_print: true

    # Stricter rules for cleanup
    unnecessary_null_checks: true
    unnecessary_this: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true

    # Robustness & Style
    cancel_subscriptions: true
    close_sinks: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    await_only_futures: true
    camel_case_types: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    unnecessary_const: true
    unnecessary_new: true
    void_checks: true
    use_build_context_synchronously: true
    avoid_unused_constructor_parameters: true
